Collection
NorthDragons/andersen-study pull request #2
Opened 2022-10-28 13:00 UTC by NorthDragons

The main methods of LinkedList,ArrayList,TreeMap collections are implemented.

Created unit tests for these methods

2022-10-30 19:03 UTC, ALnOUA requested changes

2022-10-30 20:51 UTC, ALnOUA requested changes

2022-10-30 20:51 UTC, ALnOUA commented on study/src/main/java/com/study/andersen/collection/arraylist/ArrayList.java
> +            for (int index = 0; index < elementData.length; index++) {
In loops and lambdas it`s ok to use short names, it`s not recommended  to use it in other places

2022-10-30 21:37 UTC, NorthDragons commented on study/src/main/java/com/study/andersen/collection/arraylist/ArrayList.java
> +                    initialCapacity);
Should I replace exception with logging? or throw an exception and write log?

2022-11-01 17:19 UTC, ALnOUA approved these changes

2022-11-01 17:30 UTC, merged